### PR TITLE
fix: Correct adapter name in lab sessions

### PR DESCRIPTION
**Pull request by everly-gif**
Signed-off-by: Everly Precia Suresh <77877486+everly-gif@users.noreply.github.com>

**Description**

While going through the tutorial for [Working with Meshery and Istio](https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-istio) using the istio adapter I found a small typo in the lab sessions. This PR addresses it. Instead of saying **Istio**, it says **Linkerd** which should be corrected. 

 Found some other lab sessions had the same issue as well, addressed the same

Let me know if there is anything else needed from my side. 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks for this, @everly-gif 👏

**Comment by asubedy** [comment]
Thank you @everly-gif, just few things, there are some other instances on the labs that have a different adapter name, could you fix that too.

**Comment by everly-gif** [comment]
Hi @asubedy I'm not able to find anymore typos , could you point me to where?

**Comment by everly-gif** [comment]
@asubedy any update?

**Comment by asubedy** [comment]
Hi, @everly-gif  it seems all typos have been solved 👍

**Review by asubedy — APPROVED** [review]
LGTM

**Comment by everly-gif** [comment]
Okay great ! Thank you ! Lets get this merged 💪

**Comment by everly-gif** [comment]
@leecalcote can this merged? Now that it has been approved?

**Review by leecalcote — APPROVED** [review]
Sounds great, @everly-gif. 👏

**Pull request merged**
