### PR TITLE
kuma install image

### PR DESCRIPTION
**Pull request by vishal267**
Signed-off-by: VIshal Arora <vishalarora@HGB3U9K.local>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — CHANGES_REQUESTED** [review]
Please confirm you already added the file, I saw is an empty file.

**Comment by vishal267** [comment]
> Please confirm you already added the file, I saw is an empty file.

yes in my system is showing a non empty file. pushing the changes again .  
ls -lrtSh install-kuma.png
-rw-r--r--@ 1 vishalarora  staff   318K Mar 12 11:59 install-kuma.png

**Comment by vishal267** [comment]
> > Please confirm you already added the file, I saw is an empty file.
> 
> yes in my system is showing a non empty file. pushing the changes again .
> ls -lrtSh install-kuma.png
> -rw-r--r--@ 1 vishalarora staff 318K Mar 12 11:59 install-kuma.png

added the file again , able to view the file "https://github.com/layer5io/service-mesh-labs/blob/31469e0127bd28f09632268ad16590538499be2c/Meshery-Adapters/kuma-meshery-adapter/assets/install-kuma.png"

**Review by Aisuko — APPROVED** [review]
LGTM

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
@leecalcote I do not have permission , please merge this to the master.

**Pull request merged**
