### PR TITLE
fixed bug: Meshery bash installer incorrect #67

### LINKED ISSUE #67: Meshery bash installer incorrect
**Description**
From Vaibhav Bisht:

> The curl install url is incorrect.
> currently it is: curl -L https://git.io/meshery | ADAPTERS=istio PLATFORM=kubernetes bash -

**Expected Behavior**
> it should be curl -L https://meshery.io/install | ADAPTERS=istio PLATFORM=kubernetes bash - (edited)

### PR DESCRIPTION
**Pull request by vaibhav135**
Signed-off-by: vaibhav bisht <vaibhav@aus.co.in>

**Description**

This PR fixes #67 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Shazam! ⚡ Looks good to me, @vaibhav135 👍

**Comment by leecalcote** [comment]
Whoo-hoo! 🎈 @vaibhav135 👏

**Comment by vaibhav135** [comment]
@leecalcote Thanks. Finally my first open source contribution.

**Comment by leecalcote** [comment]
🥇

**Pull request merged**
